# Generated by Django 2.0 on 2018-02-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=16, null=True)),
                ('text_symbol', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyQuantityProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coin.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('coin_name', models.CharField(max_length=32)),
                ('coin_symbol', models.CharField(max_length=8)),
                ('rank', models.IntegerField()),
                ('available_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('market_cap', models.ManyToManyField(related_name='coin_market_cap', to='Coin.CurrencyQuantityProxy')),
                ('price', models.ManyToManyField(related_name='coin_price', to='Coin.CurrencyQuantityProxy')),
                ('volume', models.ManyToManyField(related_name='coin_volume', to='Coin.CurrencyQuantityProxy')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='logs',
            field=models.ManyToManyField(to='Coin.Log'),
        ),
    ]
