# Generated by Django 2.0 on 2018-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='percent_change_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
